name: template
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 999.999.999+999

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # localization
  flutter_localizations:
    sdk: flutter
  # mostly for date format
  intl: ^0.18.0

  # update checkers
  upgrader: ^6.2.0
  in_app_update: ^4.0.1 # background android update use play.core

  # navigation and deep linking
  auto_route: ^6.0.0


  # Work with data
  # immutable object and copy with
  freezed_annotation: ^2.2.0

  json_annotation: ^4.6.0

  # persistent storage
  hive: ^2.0.0
  hive_flutter: ^1.0.0

  # work with files and access to app directory
  path_provider: ^2.0.1

  # networking
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.0
  dio_cache_interceptor_hive_store: ^3.2.0
  dio_cache_interceptor_file_store: ^1.2.0
  dio_smart_retry: ^5.0.0

  # error handling and report
  sentry_flutter: ^7.4.1

  # notifications
  # lock version cause ios critical bug
  # https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/608
  onesignal_flutter: ^3.5.1 

  # work with stream
  rxdart: ^0.27.1

  # yep it's async button
  async_button_builder: ^3.0.0+1

  # permission handler
  permission_handler: ^10.0.0

  # quick action
  quick_actions: ^1.0.1

  # for language select
  country_icons: ^2.0.2

  riverpod: ^2.3.2
  flutter_riverpod: ^2.3.2
  
  collection: ^1.15.0

  slang: ^3.15.0
  slang_flutter: ^3.15.0
  
  # stream to sliver list\grid
  sliver_stream_builder: ^0.4.0
  the_splash: ^0.3.1
  riverpod_persistent_state: ^2.0.0
  guarded_core: ^0.4.1

  # this is already in depency tree :(
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.7
  sentry_dio: ^7.4.1
  flutter_animate: ^4.1.1+1
  window_manager: ^0.3.4

  # your application dependencies

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  build_runner: ^2.0.3
  
  freezed: ^2.2.0
  json_serializable: ^6.3.0
  hive_generator: ^2.0.0

  auto_route_generator: ^6.0.3

  flutter_lints: ^2.0.1
  
  icons_launcher: ^2.0.0

  slang_build_runner: ^3.5.0
  custom_lint: ^0.3.3
  riverpod_lint: ^1.1.7
   

icons_launcher:
  image_path: 'assets/config/launcher_icon.png'
  platforms: 
    android: 
      enable: true
      adaptive_background_image: 'assets/config/launcher_icon_background.png'
      adaptive_foreground_image: 'assets/config/launcher_icon_foreground.png'
      adaptive_monochrome_image: 'assets/config/launcher_icon_monochrome.png'

    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/generated/
    - flutter_native_splash.yaml