name: Release Android Build
on:
  push:
    tags:
      - v*
      - v0.*
  workflow_dispatch:
    inputs:

jobs:
  Build-With-Mixer:
    runs-on: ubuntu-latest
    # TODO uncomment for disable github releases
    # if: github.event.inputs.generate_apk == 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: fetch mixer
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'massa-org/mixer'
          file: 'mixer'
          target: /tmp/mixer
          token: ${{ secrets.GITHUB_TOKEN }}
          

      - name: make mixer executable
        run: chmod +x /tmp/mixer

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build apk with mixer
        run: /tmp/mixer build --apk -d artifacts --secrets env --version="${{ env.RELEASE_VERSION }}+$(git rev-list HEAD --count)"
        env:
          UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
          UPLOAD_KEY_PROPERTIES: ${{ secrets.UPLOAD_KEY_PROPERTIES }}

      - name: Create GH release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to telegram
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument'
          method: 'POST'
          data: '{ "chat_id": "${{ secrets.TELEGRAM_TO }}", "caption": "New release: ${{ env.RELEASE_VERSION }}" }'
          files: '{ "document": "${{ github.workspace }}/artifacts/fat.massa.apk" }'


